# Generated by Django 4.0.3 on 2022-07-24 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('introduction', models.CharField(blank=True, help_text='100자 이하의 자기소개. 생략 가능합니다.', max_length=100)),
                ('profile_img', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
    ]
