# Generated by Django 4.0.3 on 2022-07-22 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Review title', max_length=50)),
                ('content', models.TextField(help_text='Review content')),
                ('status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('DELETED', 'Deleted')], help_text='Review status', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review updated_at')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
