# Generated by Django 4.0.3 on 2022-07-24 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(help_text='Comment content', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Comment created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Comment updated_at')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Review title', max_length=50)),
                ('content', models.TextField(help_text='Review content')),
                ('status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('DELETED', 'Deleted')], default='PUBLIC', help_text='Review status', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review updated_at')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='UserReviewScrap',
            fields=[
                ('user_review_scrap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='스크랩 활성화 active/deleted', max_length=7)),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_review_scrap',
                'verbose_name_plural': 'user_review_scraps',
            },
        ),
        migrations.CreateModel(
            name='UserReviewLike',
            fields=[
                ('user_review_like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='좋아요 활성화 active/deleted', max_length=7)),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_review_like',
                'verbose_name_plural': 'user_review_likes',
            },
        ),
        migrations.CreateModel(
            name='UserCommentLike',
            fields=[
                ('user_comment_like_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=7)),
                ('comment_id', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.comment')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImg',
            fields=[
                ('review_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to=reviews.models.ReviewImg.review_img_upload_to)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Review_img status', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review_img created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review_img updated_at')),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'verbose_name': 'reveiw_img',
                'verbose_name_plural': 'review_imgs',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='review_id',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
