# Generated by Django 4.0.3 on 2022-07-22 05:39

from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_img',
            fields=[
                ('review_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to=reviews.models.Review_img.review_img_upload_to)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], help_text='Review_img status', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review_img created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review_img updated_at')),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'verbose_name': 'reveiw_img',
                'verbose_name_plural': 'review_imgs',
            },
        ),
    ]
