# Generated by Django 4.0.3 on 2022-07-22 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_user_review_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_review_scrap',
            fields=[
                ('user_review_scrap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], help_text='스크랩 활성화 active/deleted', max_length=7)),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_review_scrap',
                'verbose_name_plural': 'user_review_scraps',
            },
        ),
    ]
