# Generated by Django 4.0.3 on 2022-07-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_user_review_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(help_text='Comment content', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Comment created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Comment updated_at')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.comment')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('DELETED', 'Deleted')], default='PUBLIC', help_text='Review status', max_length=7),
        ),
        migrations.AlterField(
            model_name='review_img',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Review_img status', max_length=7),
        ),
        migrations.AlterField(
            model_name='user_review_like',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='좋아요 활성화 active/deleted', max_length=7),
        ),
        migrations.AlterField(
            model_name='user_review_scrap',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='스크랩 활성화 active/deleted', max_length=7),
        ),
        migrations.CreateModel(
            name='UserCommentLike',
            fields=[
                ('user_comment_like_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=7)),
                ('comment_id', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.comment')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='review_id',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
