# Generated by Django 4.0.6 on 2022-08-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(default='', help_text='100자 이하의 자기소개. 생략 가능합니다.', max_length=100),
        ),
    ]
