# Generated by Django 4.0.6 on 2022-07-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img_url', models.TextField()),
                ('author', models.TextField(max_length=20)),
                ('book_info', models.TextField()),
                ('isbn', models.TextField(max_length=20)),
                ('pubdate', models.DateField()),
                ('publisher', models.TextField(max_length=20)),
                ('dt_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
